version: '3.3'
services:
  post_db:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: mongo:3.2
    volumes:
      - post_db:${DB_DIR}
    networks:
      - back_net

  ui:
    image: ${USERNAME}/ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${UI_PORT}:9292/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net

  post:
    image: ${USERNAME}/post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
#    depends_on:
#      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.0.2.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.0.1.0/24"
