version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:${DB_DIR}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:latest
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:latest
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:latest
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:
networks:
  back_net:
    ipam:
      config:
        - subnet: "10.0.2.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.0.1.0/24"
